# ========== Configuración del servidor ==========
server.port=${PORT:8080}

# ========== Codificación UTF-8 ==========
spring.sql.init.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# ========== PostgreSQL ==========
spring.datasource.url=jdbc:postgresql://dpg-d86g7ugjs32c73el14ug-a.oregon-postgres.render.com/inventariodb_ntj1
spring.datasource.username=admin
spring.datasource.password=YFNHhLifnJX76kHxIZf2LGopKe8BZP3t
spring.datasource.driver-class-name=org.postgresql.Driver

# ========== JPA ==========
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ========== Swagger / OpenAPI ==========
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method